sudo: false
notifications:
  email: false
matrix:
  include:
   - language: java
     jdk: oraclejdk8
     script:
       - ./gradlew build -i

   - language: node_js
     node_js: 10
     script:
       - cd web && npm run build
