swagger: "2.0"
info:
  description: "https://github.com/tomasbjerre/pom-dependency-analyzer-web"
  version: "1.0.0"
  title: "Pom Dependency Analyzer Web"
  termsOfService: "https://github.com/tomasbjerre/pom-dependency-analyzer-web/blob/master/LICENSE"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "tomasbjerre.github.io"
basePath: "/pom-dependency-analyzer-web/api"
tags:
- name: "pet"
  description: "Everything about your Pets"
schemes:
- "https"
- "http"
paths:
  /pdaw/groups.json:
    get:
      summary: "Get list of groups"
      operationId: "getGroupIds"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Group"
  /pdaw/groups/{groupId}/artifacts.json:
    get:
      summary: "Get list of artifacts"
      operationId: "getArtifacts"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Artifact"
    parameters:
    - name: groupId
      in: path
      description: The groupId
      required: true
      type: string
  /pdaw/groups/{groupId}/artifacts/{artifactId}/versions.json:
    get:
      summary: "Get list of versions"
      operationId: "getVersions"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Version"
    parameters:
    - name: groupId
      in: path
      description: The groupId
      required: true
      type: string
    - name: artifactId
      in: path
      description: The artifactId
      required: true
      type: string
  /pdaw/groups/{groupId}/artifacts/{artifactId}/versions/{version}/dependencies.json:
    get:
      summary: "Get list of dependencies"
      operationId: "getDependencies"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Dependency"
    parameters:
    - name: groupId
      in: path
      description: The groupId
      required: true
      type: string
    - name: artifactId
      in: path
      description: The artifactId
      required: true
      type: string
    - name: version
      in: path
      description: The version
      required: true
      type: string
  /pdaw/groups/{groupId}/artifacts/{artifactId}/versions/{version}/dependents.json:
    get:
      summary: "Get list of dependents"
      operationId: "getDependents"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Dependency"
    parameters:
    - name: groupId
      in: path
      description: The groupId
      required: true
      type: string
    - name: artifactId
      in: path
      description: The artifactId
      required: true
      type: string
    - name: version
      in: path
      description: The version
      required: true
      type: string
definitions:
  Group:
    type: "object"
    required:
    - "groupId"
    properties:
      groupId:
        type: "string"
        example: "se.bjurr.violations"
  Artifact:
    type: "object"
    required:
    - "groupId"
    - "artifactId"
    properties:
      groupId:
        type: "string"
        example: "se.bjurr.violations"
      artifactId:
        type: "string"
        example: "violations-lib"
  Version:
    type: "object"
    required:
    - "groupId"
    - "artifactId"
    - "version"
    properties:
      groupId:
        type: "string"
        example: "se.bjurr.violations"
      artifactId:
        type: "string"
        example: "violations-lib"
      version:
        type: "string"
        example: "1.0"
  Dependency:
    type: "object"
    required:
    - "groupId"
    - "artifactId"
    - "version"
    - "type"
    - "scope"
    properties:
      groupId:
        type: "string"
        example: "se.bjurr.violations"
      artifactId:
        type: "string"
        example: "violations-lib"
      version:
        type: "string"
        example: "1.0"
      classifier:
        type: "string"
        example: "whatever"
      type:
        type: "string"
        example: "jar"
      scope:
        type: "string"
        example: "provided"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
  
